=== pcanterino/selfforum/selfforum-cgi/user/config/fo_view.dtd
<!-- ***************************************************************************
*                                                                              *
* File:         fo_view.dtd                                                    *
*                                                                              *
* Authors:      Frank Schoenmann <fs@tower.de>, 2001-05-20                     *
*                                                                              *
* Description:  n/a                                                            *
*                                                                              *
**************************************************************************** -->

<!ELEMENT   Config          (Property)>

<!ELEMENT   Property        (Variable | Property)*>
<!ATTLIST   Property
    name                    CDATA       #REQUIRED
>

<!ELEMENT   Variable        (#PCDATA)>
<!ATTLIST   Variable
    name                    CDATA       #REQUIRED
>

=== pcanterino/selfforum/selfforum-config/fo_delete.xml
<?xml version="1.0"?>
<!DOCTYPE Forum SYSTEM "fo_view.dtd">
<Config>
    <Property name="show">
        <Property name="Forum">
            <Variable name="templateFile">/home/www/htdocs/teamone.de/selfforum/cgi-config/delete.tmpl.xml</Variable>

            <Property name="assign">
                <Variable name="mainDocStart">DOC_FORUM_START</Variable>
                <Variable name="mainDocEnd">DOC_FORUM_END</Variable>
                <Variable name="loadingTime">_LOAD_TIME</Variable>
                <Variable name="cssFile">_CSS_FILE</Variable>
                <Variable name="errorDoc">DOC_ERROR</Variable>
                <Variable name="deletedDoc">DOC_DELETED</Variable>
                <Variable name="notAvailable">_N_A</Variable>
                <Variable name="occupied">_OCCUPIED</Variable>
                <Variable name="errorText">_ERROR_TEXT</Variable>
                <Variable name="action">_ACTION</Variable>
                <Variable name="deleteFailed">_DELETE_FAILED</Variable>
                <Variable name="recoverFailed">_RECOVERY_FAILED</Variable>

                <!-- deleted successfully -->
                <Variable name="ip">_IP</Variable>
                <Variable name="tid">_TID</Variable>
                <Variable name="mid">_MID</Variable>
            </Property>
        </Property>
    </Property>
</Config>

<!-- eof -->
